import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[3] / "env" / "local.env", override=False)

PPT_GENERATOR_HOME = Path.home() / ".ppt-generator"

DESIGN_SPEC_PARALLEL = int(os.environ.get("DESIGN_SPEC_PARALLEL", "8"))

# --- 디자인 스펙 생성 모델 ---
BEDROCK_DESIGN_MODEL_ID = os.environ.get(
    "BEDROCK_DESIGN_MODEL_ID", "global.anthropic.claude-opus-4-6-v1"
)
ANTHROPIC_DESIGN_MODEL_ID = os.environ.get(
    "ANTHROPIC_DESIGN_MODEL_ID", "claude-opus-4-6"
)
BEDROCK_DESIGN_MAX_TOKENS = int(os.environ.get("BEDROCK_DESIGN_MAX_TOKENS", "64000"))

# --- 아웃라인/스크립트 생성 모델 ---
BEDROCK_OUTLINE_MODEL_ID = os.environ.get(
    "BEDROCK_OUTLINE_MODEL_ID", "global.anthropic.claude-sonnet-4-6"
)
ANTHROPIC_OUTLINE_MODEL_ID = os.environ.get(
    "ANTHROPIC_OUTLINE_MODEL_ID", "claude-sonnet-4-6"
)
BEDROCK_OUTLINE_MAX_TOKENS = int(os.environ.get("BEDROCK_OUTLINE_MAX_TOKENS", "32000"))
BEDROCK_SCRIPT_MAX_TOKENS = int(os.environ.get("BEDROCK_SCRIPT_MAX_TOKENS", "32000"))
OUTLINE_THINKING_EFFORT = os.environ.get("OUTLINE_THINKING_EFFORT", "medium")

# --- 공통 ---
BEDROCK_REGION = os.environ.get("AWS_REGION", "us-east-1")

DEFAULT_NUM_SLIDES = 5
MIN_NUM_SLIDES = 3
MAX_NUM_SLIDES = 20

VALID_AUDIENCE_LEVELS = ("general", "technical", "executive")
DEFAULT_AUDIENCE_LEVEL = "general"
DEFAULT_PRESENTATION_MINUTES = 15
MIN_PRESENTATION_MINUTES = 3
MAX_PRESENTATION_MINUTES = 60

# --- Bedrock Structured Output JSON Schemas (re-export) ---

from ppt_generator.interfaces.json_schemas import OUTLINE_JSON_SCHEMA, SCRIPT_JSON_SCHEMA  # noqa: E402

# --- PPTX 수치 상수 ---

PPTX_SLIDE_WIDTH_EMU = 12_192_000   # 13.333" x 914400
PPTX_SLIDE_HEIGHT_EMU = 6_858_000   # 7.5" x 914400
PPTX_FONT_NAME = "맑은 고딕"
PPTX_MONOSPACE_FONT_NAME = "Consolas"
PPTX_BODY_FONT_SIZE_PT = 20
PPTX_TITLE_FONT_SIZE_PT = 32

PPTX_BULLET_CHAR_L0 = "\u2022"
PPTX_BULLET_MARGIN_EMU_L0 = 228600    # ~0.25in
PPTX_BULLET_INDENT_EMU_L0 = -171450
PPTX_BULLET_MARGIN_EMU_L1 = 457200    # ~0.5in
PPTX_BULLET_INDENT_EMU_L1 = -171450

SLIDES_WIDTH_PX = 1280
SLIDES_HEIGHT_PX = 720

PPTX_VALIDATE_FONT_MIN_PT = 10
PPTX_VALIDATE_FONT_MAX_PT = 44
PPTX_VALIDATE_LINE_HEIGHT_FACTOR = 2.0  # pt→px(1.33) × line-height(1.5) ≈ 2.0

SPEC_VALIDATE_OVERLAP_GAP_PX = 16          # 겹침 해소 시 최소 간격 (px)
SPEC_VALIDATE_CONTENT_CENTER_THRESHOLD = 0.65  # 콘텐츠가 박스 높이의 65% 미만이면 middle 정렬
SPEC_VALIDATE_MARGIN_PX = 64               # 슬라이드 가장자리 최소 여백 (px)

EXPORT_PX_TO_INCHES_X = 13.333 / 1280  # ~0.01042
EXPORT_PX_TO_INCHES_Y = 7.5 / 720      # ~0.01042

# --- 텍스트 측정 상수 ---

TEXT_MEASURE_PX_PER_PT = 1.333
TEXT_MEASURE_CJK_WIDTH_RATIO = 0.9
TEXT_MEASURE_LATIN_WIDTH_RATIO = 0.55
TEXT_MEASURE_MONOSPACE_WIDTH_RATIO = 0.6
TEXT_MEASURE_BULLET_INDENT_L0_PX = 24.0
TEXT_MEASURE_BULLET_INDENT_L1_PX = 48.0
TEXT_MEASURE_DEFAULT_SHAPE_PADDING_LR_PX = 4.8
TEXT_MEASURE_DEFAULT_SHAPE_PADDING_TB_PX = 2.4

PPTX_SHAPE_DEFAULT_MARGIN_LR_EMU = 45720   # ~0.05 inch
PPTX_SHAPE_DEFAULT_MARGIN_TB_EMU = 22860   # ~0.025 inch
PX_TO_EMU = 9525                            # 914400 / 96

COMPONENT_HINT_COMPLEXITY: dict[str, int] = {
    "arch_diagram": 10,
    "process_flow": 9,
    "pipeline": 8,
    "concept_list": 8,
    "quote_code": 7,
    "vs_comparison": 7,
    "summary_grid": 7,
    "step_cards": 6,
    "info_cards": 6,
    "code_block": 5,
    "two_column": 5,
    "feature_list": 4,
    "agenda": 3,
    "cta": 3,
    "bullets": 2,
    "quote": 1,
}

TEMPLATE_BG_IMAGES_DIR = Path(__file__).parent.parent / "templates" / "template_bg_images"

SLIDES_TEMPLATE_PATH = Path(__file__).parent.parent / \
    "templates" / "slides.html"
SLIDE_TEMPLATE_PATH = Path(__file__).parent.parent / \
    "templates" / "slide.html"
SLIDES_CONTAINER_TEMPLATE_PATH = Path(__file__).parent.parent / \
    "templates" / "slides_container.html"

SLIDE_WIDTH = 1280
SLIDE_HEIGHT = 720
SLIDE_FOOTER_HEIGHT = 48

# --- 프롬프트 상수 (prompts 모듈에서 re-export) ---

from ppt_generator.interfaces.prompts import (  # noqa: E402
    DESIGN_SPEC_BATCH_USER_PROMPT_TEMPLATE,
    DESIGN_SPEC_SYSTEM_PROMPT,
    DESIGN_SPEC_USER_PROMPT_TEMPLATE,
    DESIGN_SUMMARY_USER_PROMPT_TEMPLATE,
    OUTLINE_SYSTEM_PROMPT,
    OUTLINE_USER_PROMPT_TEMPLATE,
    SCRIPT_SYSTEM_PROMPT,
    SCRIPT_USER_PROMPT_TEMPLATE,
)

__all__ = [
    # Design model settings
    "BEDROCK_DESIGN_MODEL_ID", "ANTHROPIC_DESIGN_MODEL_ID",
    "BEDROCK_DESIGN_MAX_TOKENS",
    # Outline/Script model settings
    "BEDROCK_OUTLINE_MODEL_ID", "ANTHROPIC_OUTLINE_MODEL_ID",
    "BEDROCK_OUTLINE_MAX_TOKENS", "BEDROCK_SCRIPT_MAX_TOKENS",
    "OUTLINE_THINKING_EFFORT",
    # Common
    "BEDROCK_REGION",
    # Numeric constants
    "DEFAULT_NUM_SLIDES", "MIN_NUM_SLIDES", "MAX_NUM_SLIDES",
    "VALID_AUDIENCE_LEVELS", "DEFAULT_AUDIENCE_LEVEL",
    "DEFAULT_PRESENTATION_MINUTES", "MIN_PRESENTATION_MINUTES", "MAX_PRESENTATION_MINUTES",
    "PPTX_SLIDE_WIDTH_EMU", "PPTX_SLIDE_HEIGHT_EMU", "PPTX_FONT_NAME", "PPTX_MONOSPACE_FONT_NAME",
    "PPTX_BODY_FONT_SIZE_PT", "PPTX_TITLE_FONT_SIZE_PT",
    "PPTX_BULLET_CHAR_L0", "PPTX_BULLET_MARGIN_EMU_L0", "PPTX_BULLET_INDENT_EMU_L0",
    "PPTX_BULLET_MARGIN_EMU_L1", "PPTX_BULLET_INDENT_EMU_L1",
    "SLIDES_WIDTH_PX", "SLIDES_HEIGHT_PX",
    "PPTX_SHAPE_DEFAULT_MARGIN_LR_EMU", "PPTX_SHAPE_DEFAULT_MARGIN_TB_EMU", "PX_TO_EMU",
    "PPTX_VALIDATE_FONT_MIN_PT", "PPTX_VALIDATE_FONT_MAX_PT", "PPTX_VALIDATE_LINE_HEIGHT_FACTOR",
    "SPEC_VALIDATE_OVERLAP_GAP_PX", "SPEC_VALIDATE_CONTENT_CENTER_THRESHOLD",
    "SPEC_VALIDATE_MARGIN_PX",
    "EXPORT_PX_TO_INCHES_X", "EXPORT_PX_TO_INCHES_Y",
    # Text measurement constants
    "TEXT_MEASURE_PX_PER_PT", "TEXT_MEASURE_CJK_WIDTH_RATIO",
    "TEXT_MEASURE_LATIN_WIDTH_RATIO", "TEXT_MEASURE_MONOSPACE_WIDTH_RATIO",
    "TEXT_MEASURE_BULLET_INDENT_L0_PX", "TEXT_MEASURE_BULLET_INDENT_L1_PX",
    "TEXT_MEASURE_DEFAULT_SHAPE_PADDING_LR_PX", "TEXT_MEASURE_DEFAULT_SHAPE_PADDING_TB_PX",
    "TEMPLATE_BG_IMAGES_DIR",
    "SLIDES_TEMPLATE_PATH", "SLIDE_TEMPLATE_PATH", "SLIDES_CONTAINER_TEMPLATE_PATH",
    "SLIDE_WIDTH", "SLIDE_HEIGHT", "SLIDE_FOOTER_HEIGHT",
    # JSON schemas
    "OUTLINE_JSON_SCHEMA", "SCRIPT_JSON_SCHEMA",
    # Prompts (re-exported from prompts module)
    "DESIGN_SPEC_BATCH_USER_PROMPT_TEMPLATE",
    "DESIGN_SPEC_SYSTEM_PROMPT", "DESIGN_SPEC_USER_PROMPT_TEMPLATE",
    "DESIGN_SUMMARY_USER_PROMPT_TEMPLATE",
    "OUTLINE_SYSTEM_PROMPT", "OUTLINE_USER_PROMPT_TEMPLATE",
    "SCRIPT_SYSTEM_PROMPT", "SCRIPT_USER_PROMPT_TEMPLATE",
    # Paths
    "PPT_GENERATOR_HOME",
    # Parallelism
    "DESIGN_SPEC_PARALLEL",
    # Complexity
    "COMPONENT_HINT_COMPLEXITY",
]
