import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv(Path(__file__).resolve().parents[3] / "env" / "local.env", override=False)

PPT_GENERATOR_HOME = Path.home() / ".ppt-generator"

DESIGN_SPEC_PARALLEL = int(os.environ.get("DESIGN_SPEC_PARALLEL", "8"))

# --- Visual QA ---
VISUAL_QA_PARALLEL = int(os.environ.get("VISUAL_QA_PARALLEL", "8"))
VISUAL_QA_MAX_ITERATIONS = int(os.environ.get("VISUAL_QA_MAX_ITERATIONS", "2"))

# --- Timeouts (seconds) ---
DESIGN_SPEC_TIMEOUT = int(os.environ.get("DESIGN_SPEC_TIMEOUT", "300"))
SCREENSHOT_TIMEOUT = int(os.environ.get("SCREENSHOT_TIMEOUT", "60"))
VISUAL_QA_PHASE_TIMEOUT = int(os.environ.get("VISUAL_QA_PHASE_TIMEOUT", "600"))

# Visual QA analysis model (Haiku — lightweight classification)
BEDROCK_VISUAL_QA_ANALYSIS_MODEL_ID = os.environ.get(
    "BEDROCK_VISUAL_QA_ANALYSIS_MODEL_ID",
    "global.anthropic.claude-haiku-4-5-20251001-v1:0",
)
ANTHROPIC_VISUAL_QA_ANALYSIS_MODEL_ID = os.environ.get(
    "ANTHROPIC_VISUAL_QA_ANALYSIS_MODEL_ID", "claude-haiku-4-5-20251001"
)
BEDROCK_VISUAL_QA_ANALYSIS_MAX_TOKENS = int(
    os.environ.get("BEDROCK_VISUAL_QA_ANALYSIS_MAX_TOKENS", "8192")
)
VISUAL_QA_VIEWPORT_WIDTH = 1280
VISUAL_QA_VIEWPORT_HEIGHT = 720

# --- Design spec generation model ---
BEDROCK_DESIGN_MODEL_ID = os.environ.get(
    "BEDROCK_DESIGN_MODEL_ID", "global.anthropic.claude-sonnet-4-6"
)
ANTHROPIC_DESIGN_MODEL_ID = os.environ.get(
    "ANTHROPIC_DESIGN_MODEL_ID", "claude-sonnet-4-6"
)
BEDROCK_DESIGN_MAX_TOKENS = int(os.environ.get("BEDROCK_DESIGN_MAX_TOKENS", "64000"))
BEDROCK_REVIEW_MAX_TOKENS = int(os.environ.get("BEDROCK_REVIEW_MAX_TOKENS", "4096"))

# --- Outline/script generation model ---
BEDROCK_OUTLINE_MODEL_ID = os.environ.get(
    "BEDROCK_OUTLINE_MODEL_ID", "global.anthropic.claude-sonnet-4-6"
)
ANTHROPIC_OUTLINE_MODEL_ID = os.environ.get(
    "ANTHROPIC_OUTLINE_MODEL_ID", "claude-sonnet-4-6"
)
BEDROCK_OUTLINE_MAX_TOKENS = int(os.environ.get("BEDROCK_OUTLINE_MAX_TOKENS", "32000"))
BEDROCK_SCRIPT_MAX_TOKENS = int(os.environ.get("BEDROCK_SCRIPT_MAX_TOKENS", "32000"))

# --- Common ---
BEDROCK_REGION = os.environ.get("AWS_REGION", "us-east-1")

DEFAULT_NUM_SLIDES = 5
MIN_NUM_SLIDES = 3
MAX_NUM_SLIDES = 20

VALID_AUDIENCE_TYPES = ("general", "technical", "executive")
DEFAULT_AUDIENCE_TYPE = "general"
DEFAULT_PRESENTATION_MINUTES = 15
MIN_PRESENTATION_MINUTES = 3
MAX_PRESENTATION_MINUTES = 60

# --- Bedrock Structured Output JSON Schemas (re-export) ---

from ppt_generator.interfaces.json_schemas import (
    OUTLINE_JSON_SCHEMA,
    SCRIPT_JSON_SCHEMA,
)  # noqa: E402

# --- PPTX numeric constants ---

PPTX_SLIDE_WIDTH_EMU = 12_192_000  # 13.333" x 914400
PPTX_SLIDE_HEIGHT_EMU = 6_858_000  # 7.5" x 914400
PPTX_FONT_NAME = "맑은 고딕"
PPTX_MONOSPACE_FONT_NAME = "Consolas"
PPTX_BODY_FONT_SIZE_PT = 20
PPTX_TITLE_FONT_SIZE_PT = 32

PPTX_BULLET_CHAR_L0 = "\u2022"
PPTX_BULLET_MARGIN_EMU_L0 = 228600  # ~0.25in
PPTX_BULLET_INDENT_EMU_L0 = -171450
PPTX_BULLET_MARGIN_EMU_L1 = 457200  # ~0.5in
PPTX_BULLET_INDENT_EMU_L1 = -171450

SLIDES_WIDTH_PX = 1280
SLIDES_HEIGHT_PX = 720

PPTX_VALIDATE_FONT_MIN_PT = 10
PPTX_VALIDATE_FONT_MAX_PT = 44
PPTX_VALIDATE_LINE_HEIGHT_FACTOR = 2.0  # pt→px(1.33) × line-height(1.5) ≈ 2.0

# Card-specific font floors (enforced by validator for shapes with fill_color)
CARD_TITLE_FONT_MIN_PT = 18
CARD_BODY_FONT_MIN_PT = 16
SECTION_LABEL_FONT_MIN_PT = 14
SLIDE_TITLE_FONT_MIN_PT = 24

SPEC_VALIDATE_MARGIN_PX = 64  # Min margin from slide edges (px)
SPEC_VALIDATE_MARGIN_BOTTOM_PX = 32  # Min bottom margin (px)
SPEC_VALIDATE_MIN_GAP_PX = 8  # Min gap between text shapes (px)

EXPORT_PX_TO_INCHES_X = 13.333 / 1280  # ~0.01042
EXPORT_PX_TO_INCHES_Y = 7.5 / 720  # ~0.01042

# --- Text measurement constants ---

TEXT_MEASURE_PX_PER_PT = 1.333
TEXT_MEASURE_CJK_WIDTH_RATIO = 0.9
TEXT_MEASURE_LATIN_WIDTH_RATIO = 0.55
TEXT_MEASURE_MONOSPACE_WIDTH_RATIO = 0.6
TEXT_MEASURE_BULLET_INDENT_L0_PX = 24.0
TEXT_MEASURE_BULLET_INDENT_L1_PX = 48.0
TEXT_MEASURE_DEFAULT_SHAPE_PADDING_LR_PX = 4.8
TEXT_MEASURE_DEFAULT_SHAPE_PADDING_TB_PX = 2.4

PPTX_SHAPE_DEFAULT_MARGIN_LR_EMU = 45720  # ~0.05 inch
PPTX_SHAPE_DEFAULT_MARGIN_TB_EMU = 22860  # ~0.025 inch
PX_TO_EMU = 9525  # 914400 / 96
EMU_TO_PX = 1.0 / PX_TO_EMU  # inverse: EMU → px
EMU_PER_INCH = 914400
DPI = 96
IMPORT_EMU_TO_PX = DPI / EMU_PER_INCH  # EMU → px (= 1/9525)

COMPONENT_HINT_COMPLEXITY: dict[str, int] = {
    "arch_diagram": 5,
    "process_flow": 5,
    "pipeline": 4,
    "concept_list": 4,
    "quote_code": 4,
    "vs_comparison": 4,
    "summary_grid": 4,
    "step_cards": 3,
    "info_cards": 3,
    "code_block": 3,
    "two_column": 3,
    "feature_list": 2,
    "agenda": 1,
    "cta": 2,
    "bullets": 1,
    "quote": 1,
}

# --- Project directory layout ---
PROJECT_SLIDES_DIR = "slides"
PROJECT_IMAGES_DIR = "slides/images"
PROJECT_OUTLINE_DIR = "outline"
PROJECT_SCRIPT_DIR = "script"

TEMPLATE_BG_IMAGES_DIR = (
    Path(__file__).parent.parent / "templates" / "template_bg_images"
)

SLIDES_TEMPLATE_PATH = Path(__file__).parent.parent / "templates" / "slides.html"
SLIDE_TEMPLATE_PATH = Path(__file__).parent.parent / "templates" / "slide.html"
SLIDES_CONTAINER_TEMPLATE_PATH = (
    Path(__file__).parent.parent / "templates" / "slides_container.html"
)

SLIDE_WIDTH = 1280
SLIDE_HEIGHT = 720
SLIDE_FOOTER_HEIGHT = 48

# --- Prompt constants (re-exported from prompts module) ---

from ppt_generator.interfaces.prompts import (  # noqa: E402
    DESIGN_REVIEW_SYSTEM_PROMPT,
    DESIGN_SPEC_BATCH_USER_PROMPT_TEMPLATE,
    DESIGN_SPEC_SYSTEM_PROMPT,
    DESIGN_SPEC_SYSTEM_PROMPTS,
    DESIGN_SPEC_USER_PROMPT_TEMPLATE,
    DESIGN_SUMMARY_USER_PROMPT_TEMPLATE,
    OUTLINE_SYSTEM_PROMPT,
    OUTLINE_USER_PROMPT_TEMPLATE,
    SCRIPT_SYSTEM_PROMPT,
    SCRIPT_USER_PROMPT_TEMPLATE,
    VISUAL_QA_ANALYSIS_SYSTEM_PROMPT,
    VISUAL_QA_FIX_SYSTEM_PROMPT,
)

__all__ = [
    # Design model settings
    "BEDROCK_DESIGN_MODEL_ID",
    "ANTHROPIC_DESIGN_MODEL_ID",
    "BEDROCK_DESIGN_MAX_TOKENS",
    "BEDROCK_REVIEW_MAX_TOKENS",
    # Outline/Script model settings
    "BEDROCK_OUTLINE_MODEL_ID",
    "ANTHROPIC_OUTLINE_MODEL_ID",
    "BEDROCK_OUTLINE_MAX_TOKENS",
    "BEDROCK_SCRIPT_MAX_TOKENS",
    # Common
    "BEDROCK_REGION",
    # Numeric constants
    "DEFAULT_NUM_SLIDES",
    "MIN_NUM_SLIDES",
    "MAX_NUM_SLIDES",
    "VALID_AUDIENCE_TYPES",
    "DEFAULT_AUDIENCE_TYPE",
    "DEFAULT_PRESENTATION_MINUTES",
    "MIN_PRESENTATION_MINUTES",
    "MAX_PRESENTATION_MINUTES",
    "PPTX_SLIDE_WIDTH_EMU",
    "PPTX_SLIDE_HEIGHT_EMU",
    "PPTX_FONT_NAME",
    "PPTX_MONOSPACE_FONT_NAME",
    "PPTX_BODY_FONT_SIZE_PT",
    "PPTX_TITLE_FONT_SIZE_PT",
    "PPTX_BULLET_CHAR_L0",
    "PPTX_BULLET_MARGIN_EMU_L0",
    "PPTX_BULLET_INDENT_EMU_L0",
    "PPTX_BULLET_MARGIN_EMU_L1",
    "PPTX_BULLET_INDENT_EMU_L1",
    "SLIDES_WIDTH_PX",
    "SLIDES_HEIGHT_PX",
    "PPTX_SHAPE_DEFAULT_MARGIN_LR_EMU",
    "PPTX_SHAPE_DEFAULT_MARGIN_TB_EMU",
    "PX_TO_EMU",
    "EMU_TO_PX",
    "EMU_PER_INCH",
    "DPI",
    "IMPORT_EMU_TO_PX",
    "PPTX_VALIDATE_FONT_MIN_PT",
    "PPTX_VALIDATE_FONT_MAX_PT",
    "PPTX_VALIDATE_LINE_HEIGHT_FACTOR",
    "CARD_TITLE_FONT_MIN_PT",
    "CARD_BODY_FONT_MIN_PT",
    "SECTION_LABEL_FONT_MIN_PT",
    "SLIDE_TITLE_FONT_MIN_PT",
    "SPEC_VALIDATE_MARGIN_PX",
    "SPEC_VALIDATE_MARGIN_BOTTOM_PX",
    "SPEC_VALIDATE_MIN_GAP_PX",
    "EXPORT_PX_TO_INCHES_X",
    "EXPORT_PX_TO_INCHES_Y",
    # Text measurement constants
    "TEXT_MEASURE_PX_PER_PT",
    "TEXT_MEASURE_CJK_WIDTH_RATIO",
    "TEXT_MEASURE_LATIN_WIDTH_RATIO",
    "TEXT_MEASURE_MONOSPACE_WIDTH_RATIO",
    "TEXT_MEASURE_BULLET_INDENT_L0_PX",
    "TEXT_MEASURE_BULLET_INDENT_L1_PX",
    "TEXT_MEASURE_DEFAULT_SHAPE_PADDING_LR_PX",
    "TEXT_MEASURE_DEFAULT_SHAPE_PADDING_TB_PX",
    "PROJECT_SLIDES_DIR",
    "PROJECT_IMAGES_DIR",
    "PROJECT_OUTLINE_DIR",
    "PROJECT_SCRIPT_DIR",
    "TEMPLATE_BG_IMAGES_DIR",
    "SLIDES_TEMPLATE_PATH",
    "SLIDE_TEMPLATE_PATH",
    "SLIDES_CONTAINER_TEMPLATE_PATH",
    "SLIDE_WIDTH",
    "SLIDE_HEIGHT",
    "SLIDE_FOOTER_HEIGHT",
    # JSON schemas
    "OUTLINE_JSON_SCHEMA",
    "SCRIPT_JSON_SCHEMA",
    # Prompts (re-exported from prompts module)
    "DESIGN_REVIEW_SYSTEM_PROMPT",
    "DESIGN_SPEC_BATCH_USER_PROMPT_TEMPLATE",
    "DESIGN_SPEC_SYSTEM_PROMPT",
    "DESIGN_SPEC_SYSTEM_PROMPTS",
    "DESIGN_SPEC_USER_PROMPT_TEMPLATE",
    "DESIGN_SUMMARY_USER_PROMPT_TEMPLATE",
    "OUTLINE_SYSTEM_PROMPT",
    "OUTLINE_USER_PROMPT_TEMPLATE",
    "SCRIPT_SYSTEM_PROMPT",
    "SCRIPT_USER_PROMPT_TEMPLATE",
    "VISUAL_QA_ANALYSIS_SYSTEM_PROMPT",
    "VISUAL_QA_FIX_SYSTEM_PROMPT",
    # Paths
    "PPT_GENERATOR_HOME",
    # Parallelism
    "DESIGN_SPEC_PARALLEL",
    # Visual QA
    "VISUAL_QA_MAX_ITERATIONS",
    "VISUAL_QA_VIEWPORT_WIDTH",
    "VISUAL_QA_VIEWPORT_HEIGHT",
    "BEDROCK_VISUAL_QA_ANALYSIS_MODEL_ID",
    "ANTHROPIC_VISUAL_QA_ANALYSIS_MODEL_ID",
    "BEDROCK_VISUAL_QA_ANALYSIS_MAX_TOKENS",
    # Complexity
    "COMPONENT_HINT_COMPLEXITY",
    # Timeouts
    "DESIGN_SPEC_TIMEOUT",
    "SCREENSHOT_TIMEOUT",
    "VISUAL_QA_PHASE_TIMEOUT",
]
