import json
from dataclasses import asdict

from mcp.server.fastmcp import FastMCP

from ppt_generator.interfaces.constants import DEFAULT_AUDIENCE_TYPE, DEFAULT_PRESENTATION_MINUTES
from ppt_generator.interfaces.schemas import ScriptRequest
from ppt_generator.interfaces.utils import format_token_usage, parse_outline_json
from ppt_generator.tools.project.service import ProjectService
from ppt_generator.tools.script.service import ScriptService


def register_script_tools(mcp: FastMCP, script_service: ScriptService, project_service: ProjectService) -> None:
    @mcp.tool()
    def generate_script(project_id: str = "", outline_json: str = "") -> str:
        """Generates speaker notes (script) for each slide based on the outline.

        Takes the outline JSON generated by generate_outline as input and produces
        a natural presentation script, returning the outline JSON with speaker_notes populated.

        **Precondition: Only call this after showing the generate_outline result to the user and getting confirmation.**
        This tool should only be called when the user has confirmed they are satisfied with the outline structure.

        Args:
            project_id: Project ID. If specified, automatically loads from the saved outline.json.
            outline_json: Slide outline JSON string. Can be omitted if project_id is specified.

        Returns:
            JSON string containing script_path and project_id
        """
        if outline_json:
            outline = parse_outline_json(outline_json)
        elif project_id:
            _, proj_dir = project_service.resolve_project_dir(project_id)
            raw = project_service.load_outline(proj_dir)
            outline = parse_outline_json(raw)
        else:
            raise ValueError("Either outline_json or project_id must be provided.")

        # Load audience_type, presentation_minutes, purpose from project metadata
        audience_type = DEFAULT_AUDIENCE_TYPE
        presentation_minutes = DEFAULT_PRESENTATION_MINUTES
        purpose = ""
        if project_id:
            try:
                _, proj_dir = project_service.resolve_project_dir(project_id)
                metadata = project_service.load_metadata(proj_dir)
                audience_type = metadata.audience_type
                presentation_minutes = metadata.presentation_minutes
                purpose = metadata.purpose
            except (FileNotFoundError, Exception):
                pass

        request = ScriptRequest(
            outline=outline,
            audience_type=audience_type,
            presentation_minutes=presentation_minutes,
            purpose=purpose,
        )
        response = script_service.generate(request)
        result = json.dumps(
            {"slides": [asdict(s) for s in response.slides]},
            ensure_ascii=False,
            indent=2,
        )

        project_id, project_dir = project_service.resolve_project_dir(project_id)
        project_service.save_script(project_dir, result)
        project_service.update_step(project_dir, "script")

        resp: dict = {
            "script_path": str(project_dir / "script"),
            "project_id": project_id,
        }
        usage = format_token_usage(script_service.last_token_usage)
        if usage:
            resp["token_usage"] = usage
        return json.dumps(resp, ensure_ascii=False)


