"""프롬프트 상수 모듈."""

from ppt_generator.interfaces.prompts.outline_prompts import (
    OUTLINE_SYSTEM_PROMPT,
    OUTLINE_USER_PROMPT_TEMPLATE,
)
from ppt_generator.interfaces.prompts.pptx_prompts import (
    PPTX_CONVERT_SYSTEM_PROMPT,
    PPTX_CONVERT_USER_PROMPT_TEMPLATE,
    PPTX_CONVERT_USER_PROMPT_WITH_IMAGE_TEMPLATE,
)
from ppt_generator.interfaces.prompts.script_prompts import (
    SCRIPT_SYSTEM_PROMPT,
    SCRIPT_USER_PROMPT_TEMPLATE,
)
from ppt_generator.interfaces.prompts.slides_prompts import (
    SLIDES_BATCH_USER_PROMPT_TEMPLATE,
    SLIDES_DESIGN_SUMMARY_PROMPT,
    SLIDES_MAX_PER_BATCH,
    SLIDES_MODIFY_SINGLE_USER_PROMPT_TEMPLATE,
    SLIDES_MODIFY_SYSTEM_PROMPT,
    SLIDES_MODIFY_USER_PROMPT_TEMPLATE,
    SLIDES_SYSTEM_PROMPT,
    SLIDES_USER_PROMPT_TEMPLATE,
)

__all__ = [
    "OUTLINE_SYSTEM_PROMPT",
    "OUTLINE_USER_PROMPT_TEMPLATE",
    "PPTX_CONVERT_SYSTEM_PROMPT",
    "PPTX_CONVERT_USER_PROMPT_TEMPLATE",
    "PPTX_CONVERT_USER_PROMPT_WITH_IMAGE_TEMPLATE",
    "SCRIPT_SYSTEM_PROMPT",
    "SCRIPT_USER_PROMPT_TEMPLATE",
    "SLIDES_BATCH_USER_PROMPT_TEMPLATE",
    "SLIDES_DESIGN_SUMMARY_PROMPT",
    "SLIDES_MAX_PER_BATCH",
    "SLIDES_MODIFY_SINGLE_USER_PROMPT_TEMPLATE",
    "SLIDES_MODIFY_SYSTEM_PROMPT",
    "SLIDES_MODIFY_USER_PROMPT_TEMPLATE",
    "SLIDES_SYSTEM_PROMPT",
    "SLIDES_USER_PROMPT_TEMPLATE",
]
